package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/DBenYaakov/WriterRobot/internal/bezier"
)

type options struct {
	output      string
	x           float64
	y           float64
	rowSpacing  float64
	tolerances  []float64
	drawFeed    int
	penFeed     int
	liftFeed    int
	penDwellSec float64
}

type path []bezier.Cubic

func main() { os.Exit(run()) }

func run() int {
	var (
		output      = flag.String("output", "testdata/bezier-calibration.gcode", "output G-code file")
		x           = flag.Float64("x", 25, "left edge in machine millimeters")
		y           = flag.Float64("y", -20, "top edge in machine millimeters (normally negative)")
		rowSpacing  = flag.Float64("row-spacing", 35, "vertical distance between tolerance rows in millimeters")
		tolerances  = flag.String("tolerances", "0.50,0.25,0.10,0.05", "comma-separated flattening tolerances in millimeters")
		drawFeed    = flag.Int("draw-feed", 600, "drawing feed rate in millimeters per minute")
		penFeed     = flag.Int("pen-feed", 200, "pen-down feed rate in millimeters per minute")
		liftFeed    = flag.Int("lift-feed", 300, "pen-up feed rate in millimeters per minute")
		penDwellSec = flag.Float64("pen-dwell", 0.3, "dwell after each pen lift in seconds")
	)
	flag.Parse()
	if flag.NArg() != 0 {
		flag.Usage()
		return 2
	}

	parsedTolerances, err := parseTolerances(*tolerances)
	if err != nil {
		return fail(err)
	}
	opts := options{
		output:      *output,
		x:           *x,
		y:           *y,
		rowSpacing:  *rowSpacing,
		tolerances:  parsedTolerances,
		drawFeed:    *drawFeed,
		penFeed:     *penFeed,
		liftFeed:    *liftFeed,
		penDwellSec: *penDwellSec,
	}
	if err := validate(opts); err != nil {
		return fail(err)
	}
	if err := generate(opts); err != nil {
		return fail(err)
	}
	return 0
}

func generate(opts options) error {
	if err := os.MkdirAll(filepath.Dir(opts.output), 0o755); err != nil && filepath.Dir(opts.output) != "." {
		return fmt.Errorf("create output directory: %w", err)
	}
	file, err := os.Create(opts.output)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	writer := bufio.NewWriter(file)
	closed := false
	defer func() {
		if !closed {
			_ = file.Close()
		}
	}()

	fmt.Fprintln(writer, "; Writing Robot T-A4 adaptive cubic Bezier calibration")
	fmt.Fprintln(writer, "; Generated by ta4-bezier-test")
	fmt.Fprintln(writer, "; Rows are ordered from top to bottom in the same order printed by the generator.")
	fmt.Fprintln(writer, "G21")
	fmt.Fprintln(writer, "G90")
	fmt.Fprintf(writer, "G1 Z{{PEN_UP}} F%d\n", opts.liftFeed)

	pattern := calibrationPattern()
	for row, tolerance := range opts.tolerances {
		rowY := opts.y - float64(row)*opts.rowSpacing
		segments := 0
		fmt.Fprintf(writer, "\n; Row %d: tolerance %.3f mm\n", row+1, tolerance)
		for pathNumber, curvePath := range pattern {
			points, count, err := flattenPath(curvePath, tolerance)
			if err != nil {
				return fmt.Errorf("flatten row %d path %d: %w", row+1, pathNumber+1, err)
			}
			segments += count
			start := machinePoint(points[0], opts.x, rowY)
			fmt.Fprintf(writer, "G0 X%.3f Y%.3f\n", start.X, start.Y)
			fmt.Fprintf(writer, "G1 Z{{PEN_DOWN}} F%d\n", opts.penFeed)
			for i := 1; i < len(points); i++ {
				point := machinePoint(points[i], opts.x, rowY)
				if i == 1 {
					fmt.Fprintf(writer, "G1 X%.3f Y%.3f F%d\n", point.X, point.Y, opts.drawFeed)
				} else {
					fmt.Fprintf(writer, "G1 X%.3f Y%.3f\n", point.X, point.Y)
				}
			}
			fmt.Fprintf(writer, "G1 Z{{PEN_UP}} F%d\n", opts.liftFeed)
			fmt.Fprintf(writer, "G4 P%.3f\n", opts.penDwellSec)
		}
		fmt.Printf("Row %d: tolerance %.3f mm -> %d line segments at Y%.3f\n", row+1, tolerance, segments, rowY)
	}

	fmt.Fprintf(writer, "\nG1 Z{{PEN_UP}} F%d\n", opts.liftFeed)
	fmt.Fprintf(writer, "G4 P%.3f\n", opts.penDwellSec)
	if err := writer.Flush(); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("close output: %w", err)
	}
	closed = true
	fmt.Printf("Wrote %s\n", opts.output)
	fmt.Println("Send it with: ./ta4-send --port /dev/cu.usbmodem201912341 " + opts.output)
	return nil
}

func calibrationPattern() []path {
	return []path{
		{
			{P0: p(0, 15), P1: p(10, 2), P2: p(25, 2), P3: p(35, 15)},
		},
		{
			{P0: p(45, 22), P1: p(46, -5), P2: p(69, -5), P3: p(70, 22)},
		},
		{
			{P0: p(80, 15), P1: p(88, -3), P2: p(94, -3), P3: p(100, 15)},
			{P0: p(100, 15), P1: p(106, 33), P2: p(112, 33), P3: p(120, 15)},
		},
		{
			{P0: p(132, 15), P1: p(132, 1), P2: p(154, 1), P3: p(154, 15)},
			{P0: p(154, 15), P1: p(154, 29), P2: p(132, 29), P3: p(132, 15)},
		},
	}
}

func flattenPath(curves path, tolerance float64) ([]bezier.Point, int, error) {
	var points []bezier.Point
	segments := 0
	for index, curve := range curves {
		flattened, err := bezier.Flatten(curve, tolerance)
		if err != nil {
			return nil, 0, err
		}
		if index == 0 {
			points = append(points, flattened...)
		} else {
			points = append(points, flattened[1:]...)
		}
		segments += len(flattened) - 1
	}
	return points, segments, nil
}

func machinePoint(point bezier.Point, originX, originY float64) bezier.Point {
	return bezier.Point{X: originX + point.X, Y: originY - point.Y}
}

func p(x, y float64) bezier.Point { return bezier.Point{X: x, Y: y} }

func parseTolerances(value string) ([]float64, error) {
	parts := strings.Split(value, ",")
	result := make([]float64, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			return nil, errors.New("--tolerances contains an empty value")
		}
		tolerance, err := strconv.ParseFloat(part, 64)
		if err != nil || tolerance <= 0 {
			return nil, fmt.Errorf("invalid tolerance %q", part)
		}
		result = append(result, tolerance)
	}
	if len(result) == 0 {
		return nil, errors.New("at least one tolerance is required")
	}
	return result, nil
}

func validate(opts options) error {
	if opts.output == "" {
		return errors.New("--output cannot be empty")
	}
	if opts.rowSpacing <= 0 {
		return errors.New("--row-spacing must be greater than zero")
	}
	if opts.drawFeed <= 0 || opts.penFeed <= 0 || opts.liftFeed <= 0 {
		return errors.New("feed rates must be greater than zero")
	}
	if opts.penDwellSec < 0 {
		return errors.New("--pen-dwell cannot be negative")
	}
	return nil
}

func fail(err error) int {
	fmt.Fprintln(os.Stderr, "ta4-bezier-test:", err)
	return 1
}
