package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/DBenYaakov/WriterRobot/internal/bezier"
)

type point struct {
	X float64
	Y float64
}

type stroke []point

type options struct {
	output      string
	x           float64
	y           float64
	rowSpacing  float64
	feeds       []int
	penFeed     int
	liftFeed    int
	penDwellSec float64
	tolerance   float64
}

func main() { os.Exit(run()) }

func run() int {
	var (
		output      = flag.String("output", "testdata/motion-calibration.gcode", "output G-code file")
		x           = flag.Float64("x", 20, "left edge in machine millimeters")
		y           = flag.Float64("y", -20, "top edge in machine millimeters (normally negative)")
		rowSpacing  = flag.Float64("row-spacing", 40, "vertical distance between feed-rate rows in millimeters")
		feeds       = flag.String("feeds", "200,400,600,800,1000,1200", "comma-separated drawing feed rates in millimeters per minute")
		penFeed     = flag.Int("pen-feed", 200, "pen-down feed rate in millimeters per minute")
		liftFeed    = flag.Int("lift-feed", 300, "pen-up feed rate in millimeters per minute")
		penDwellSec = flag.Float64("pen-dwell", 0.3, "dwell after each pen lift in seconds")
		tolerance   = flag.Float64("tolerance", 0.10, "Bezier flattening tolerance in millimeters")
	)
	flag.Parse()
	if flag.NArg() != 0 {
		flag.Usage()
		return 2
	}

	parsedFeeds, err := parseFeeds(*feeds)
	if err != nil {
		return fail(err)
	}
	opts := options{
		output:      *output,
		x:           *x,
		y:           *y,
		rowSpacing:  *rowSpacing,
		feeds:       parsedFeeds,
		penFeed:     *penFeed,
		liftFeed:    *liftFeed,
		penDwellSec: *penDwellSec,
		tolerance:   *tolerance,
	}
	if err := validate(opts); err != nil {
		return fail(err)
	}
	if err := generate(opts); err != nil {
		return fail(err)
	}
	return 0
}

func generate(opts options) error {
	dir := filepath.Dir(opts.output)
	if dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output directory: %w", err)
		}
	}
	file, err := os.Create(opts.output)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	writer := bufio.NewWriter(file)
	closed := false
	defer func() {
		if !closed {
			_ = file.Close()
		}
	}()

	fmt.Fprintln(writer, "; Writing Robot T-A4 motion/feed-rate calibration")
	fmt.Fprintln(writer, "; Generated by ta4-motion-test")
	fmt.Fprintln(writer, "; Rows are ordered from top to bottom in the same order printed by the generator.")
	fmt.Fprintln(writer, "; Each row: horizontal, vertical, diagonal, sharp-corner box, 4 mm circle, 18 mm circle, spiral, sweeping S-curve.")
	fmt.Fprintln(writer, "G21")
	fmt.Fprintln(writer, "G90")
	fmt.Fprintf(writer, "G1 Z{{PEN_UP}} F%d\n", opts.liftFeed)

	pattern, err := calibrationPattern(opts.tolerance)
	if err != nil {
		return err
	}
	for row, feed := range opts.feeds {
		rowY := opts.y - float64(row)*opts.rowSpacing
		fmt.Fprintf(writer, "\n; Row %d: drawing feed F%d\n", row+1, feed)
		for _, s := range pattern {
			if len(s) < 2 {
				continue
			}
			start := machinePoint(s[0], opts.x, rowY)
			fmt.Fprintf(writer, "G0 X%.3f Y%.3f\n", start.X, start.Y)
			fmt.Fprintf(writer, "G1 Z{{PEN_DOWN}} F%d\n", opts.penFeed)
			for i := 1; i < len(s); i++ {
				p := machinePoint(s[i], opts.x, rowY)
				if i == 1 {
					fmt.Fprintf(writer, "G1 X%.3f Y%.3f F%d\n", p.X, p.Y, feed)
				} else {
					fmt.Fprintf(writer, "G1 X%.3f Y%.3f\n", p.X, p.Y)
				}
			}
			fmt.Fprintf(writer, "G1 Z{{PEN_UP}} F%d\n", opts.liftFeed)
			fmt.Fprintf(writer, "G4 P%.3f\n", opts.penDwellSec)
		}
		fmt.Printf("Row %d: F%d at Y%.3f\n", row+1, feed, rowY)
	}

	fmt.Fprintf(writer, "\nG1 Z{{PEN_UP}} F%d\n", opts.liftFeed)
	fmt.Fprintf(writer, "G4 P%.3f\n", opts.penDwellSec)
	if err := writer.Flush(); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("close output: %w", err)
	}
	closed = true
	fmt.Printf("Wrote %s\n", opts.output)
	fmt.Println("Send it with: ./.build/ta4-send --port /dev/cu.usbmodem201912341 " + opts.output)
	return nil
}

func calibrationPattern(tolerance float64) ([]stroke, error) {
	pattern := []stroke{
		{{0, 8}, {22, 8}},
		{{27, 2}, {27, 18}},
		{{32, 18}, {48, 2}},
		{{54, 3}, {70, 3}, {70, 17}, {54, 17}, {54, 3}},
		circle(78, 10, 2, 24),
		circle(94, 10, 9, 64),
		spiral(118, 10, 1, 9, 2.25, 80),
	}

	curves := []bezier.Cubic{
		{P0: bezier.Point{X: 137, Y: 10}, P1: bezier.Point{X: 145, Y: -2}, P2: bezier.Point{X: 151, Y: -2}, P3: bezier.Point{X: 157, Y: 10}},
		{P0: bezier.Point{X: 157, Y: 10}, P1: bezier.Point{X: 163, Y: 22}, P2: bezier.Point{X: 169, Y: 22}, P3: bezier.Point{X: 177, Y: 10}},
	}
	var sweep stroke
	for i, curve := range curves {
		points, err := bezier.Flatten(curve, tolerance)
		if err != nil {
			return nil, fmt.Errorf("flatten sweep curve: %w", err)
		}
		start := 0
		if i > 0 {
			start = 1
		}
		for _, p := range points[start:] {
			sweep = append(sweep, point{X: p.X, Y: p.Y})
		}
	}
	pattern = append(pattern, sweep)
	return pattern, nil
}

func circle(cx, cy, radius float64, segments int) stroke {
	result := make(stroke, 0, segments+1)
	for i := 0; i <= segments; i++ {
		angle := 2 * math.Pi * float64(i) / float64(segments)
		result = append(result, point{X: cx + radius*math.Cos(angle), Y: cy + radius*math.Sin(angle)})
	}
	return result
}

func spiral(cx, cy, startRadius, endRadius, turns float64, segments int) stroke {
	result := make(stroke, 0, segments+1)
	for i := 0; i <= segments; i++ {
		t := float64(i) / float64(segments)
		radius := startRadius + (endRadius-startRadius)*t
		angle := 2 * math.Pi * turns * t
		result = append(result, point{X: cx + radius*math.Cos(angle), Y: cy + radius*math.Sin(angle)})
	}
	return result
}

func machinePoint(p point, originX, originY float64) point {
	return point{X: originX + p.X, Y: originY - p.Y}
}

func parseFeeds(value string) ([]int, error) {
	parts := strings.Split(value, ",")
	result := make([]int, 0, len(parts))
	seen := make(map[int]bool)
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			return nil, errors.New("--feeds contains an empty value")
		}
		feed, err := strconv.Atoi(part)
		if err != nil || feed <= 0 {
			return nil, fmt.Errorf("invalid feed rate %q", part)
		}
		if seen[feed] {
			return nil, fmt.Errorf("duplicate feed rate %d", feed)
		}
		seen[feed] = true
		result = append(result, feed)
	}
	if len(result) == 0 {
		return nil, errors.New("at least one feed rate is required")
	}
	return result, nil
}

func validate(opts options) error {
	if opts.output == "" {
		return errors.New("--output cannot be empty")
	}
	if opts.rowSpacing <= 0 {
		return errors.New("--row-spacing must be greater than zero")
	}
	if opts.penFeed <= 0 || opts.liftFeed <= 0 {
		return errors.New("pen feed rates must be greater than zero")
	}
	if opts.penDwellSec < 0 {
		return errors.New("--pen-dwell cannot be negative")
	}
	if opts.tolerance <= 0 {
		return errors.New("--tolerance must be greater than zero")
	}
	return nil
}

func fail(err error) int {
	fmt.Fprintln(os.Stderr, "ta4-motion-test:", err)
	return 1
}
